name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  greeting_job1:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      day_of_week: monday
    steps:
      - name: "Say Hello Mona it's Monday"
        run: |
         echo "$Greeting $First_Name $GITHUB_REF_NAME. Today is $day_of_week!"
         echo $BRANCH_NAME
         echo ${BRANCH_NAME}
         echo "${{github.refname}}"
         echo "${{env.GITHUB_REF_NAME}}"
        env:
          First_Name: Mona
  
  greeting_job2:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      #day_of_week: monday
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $BRANCH_NAME!"
        env:
          First_Name: Roopa
          
  greeting_job3:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      #day_of_week: monday
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $day_of_week!"
        env:
          First_Name: Roopa
          day_of_week: monday

  greeting_job4:
      runs-on: ubuntu-latest
      env:
        Greeting: Hello
        #day_of_week: monday
      steps:
        - name: "Say Hello Mona it's Monday"
          run: |
            echo "${{secrets.DEV_NAME}}, ${{vars.CHILD_NAME}},${{secrets.UAT_KEY}},${{secrets.DEV_NAME}}"
